services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pwdpwdpwd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MyConge_development
    volumes:
      - C:\Users\AmineKotni\postgres_data:/var/lib/postgresql/data


